import React, { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import styles from './RootLayout.module.css';

import { Navbar, Footer } from '../ui';
import { LineSeparator } from '@/shared';

/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
*/


export const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Navbar />
      <LineSeparator shadowDown />

      <main className={ styles.container }>
        { children }
      </main>

      <LineSeparator />
      <Footer />
    </>
  )
}
